version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  GitHubAccessToken:
    secure: OW1vwaV9TZfKnCNF5Acpeun8lfUKbZOmu/6fM6HjJ4ubgi0RExv6vTRRbLKnXDAI
  UserName: Geroshabu
  MailAddress: oonstks@gmail.com
install:
- ps: choco install doxygen.portable
build:
  verbosity: minimal
after_build:
- cmd: >-
  git config --global user.email %MailAddress%
  git config --global user.name %UserName%
  git config --global push.default matching
  git clone --quiet https://github.com/Geroshabu/Geroshabu.github.io.git C:\projects\gh-pages
  cd C:/projects/gh-pages
  if exist html (rd html /s /q)

  doxygen C:/projects/GeroMachine/Doxyfile

  if exist latex (rd latex /s /q)
  cd html
  git add --all .
  git commit -m "auto commit doxygen products by AppVeyor" -m %APPVEYOR_REPO_COMMIT%
  git push --quiet https://%GitHubAccessToken%@github.com/Geroshabu/Geroshabu.github.io master
artifacts:
- path: GeroMachine\GeroMachineSample\bin\Release\GeroMachineSample.exe
  name: GeroMachineSample
- path: GeroMachine\GeroMachine\bin\Release\GeroMachine.dll
  name: GeroMachine
- path: html
  name: html
